version: "3.7"
services:
  app:
    image: kooldev/node:18
    command: ["npm", "run", "dev"]
    ports:
      - "${KOOL_APP_PORT:-3000}:5173"
    environment:
      ASUSER: "${KOOL_ASUSER:-0}"
      UID: "${UID:-0}"
    volumes:
      - .:/app:delegated
    networks:
      - kool_local
      - kool_global

networks:
  kool_local:
  kool_global:
    external: true
    name: "${KOOL_GLOBAL_NETWORK:-kool_global}"
